import * as Schema from '../classes/Schema';

export const sampleData: Schema.Database = {
    people: [
        {
            _id: "person1_id",
            name: "Bobby Sue",
            email: "bobbysue@gmail.com",
            customerOf: [],
        },
        {
            _id: "person2_id",
            name: "Billy Joe",
            email: "billyjoe@gmail.com",
            customerOf: ["person1_id"],
        },
        {
            _id: "person3_id",
            name: "Jimmy Shoe",
            email: "jimmyShoe@gmail.com",
            customerOf: ["person1_id"],
        },
    ],
    expenses: [
        {
            _id: "expense1_id",
            description: "expense1_description",
            userId: "person1_id",
            projectId: "project1_id",
            vendor: "expense1_vendor",
            amount: 5,
            hst: .65,
        },
        {
            _id: "expense2_id",
            description: "expense2_description",
            userId: "person1_id",
            vendor: "expense2_vendor",
            projectId: "project1_id",
            amount: 7,
            hst: .91,
        }, {
            _id: "expense3_id",
            description: "expense3_description",
            userId: "person1_id",
            projectId: "project2_id",
            vendor: "expense3_vendor",
            amount: 5,
            hst: .65,
        },
        {
            _id: "expense4_id",
            description: "expense4_description",
            userId: "person1_id",
            vendor: "expense4_vendor",
            projectId: "project2_id",
            amount: 7,
            hst: .91,
        },

    ],
    orders: [
        {
            _id: "order1_id",
            userId: "person1_id",
            customerId: "person2_id",
            vendor: "person1_id",
            projectId: "project1_id",
            items: [
                {
                    description: "item1_description",
                    quantity: 1,
                    price: 10,
                    hst: 1.3,
                },
                {
                    description: "item2_description",
                    quantity: 2,
                    price: 10,
                    hst: 1.3,
                },
            ],
            paid: true,
            paymentMethod: "cash",
            subtotal: 30,
            hst: 3.9,
        },
        {
            _id: "order2_id",
            userId: "person1_id",
            customerId: "person3_id",
            vendor: "person1_id",
            projectId: "project1_id",
            items: [
                {
                    description: "item1_description",
                    quantity: 1,
                    price: 10,
                    hst: 1.3,
                },
            ],
            paid: false,
            paymentMethod: null,
            subtotal: 10,
            hst: 1.3,
        },
        {
            _id: "order3_id",
            userId: "person1_id",
            customerId: "person2_id",
            vendor: "person1_id",
            projectId: "project2_id",
            items: [
                {
                    description: "item1_description",
                    quantity: 1,
                    price: 10,
                    hst: 1.3,
                },
                {
                    description: "item2_description",
                    quantity: 2,
                    price: 10,
                    hst: 1.3,
                },
            ],
            paid: true,
            paymentMethod: "cash",
            subtotal: 30,
            hst: 3.9,
        },
        {
            _id: "order4_id",
            userId: "person1_id",
            customerId: "person3_id",
            vendor: "person1_id",
            projectId: "project2_id",
            items: [
                {
                    description: "item1_description",
                    quantity: 1,
                    price: 10,
                    hst: 1.3,
                },
            ],
            paid: false,
            paymentMethod: null,
            subtotal: 10,
            hst: 1.3,
        },

    ],
    projects: [
        {
            '_id': "project1_id",
            'userId': "person1_id",
            "startDate": "Sun May 17 2020 00:02:37 GMT-0400 (Eastern Daylight Time)",
            "endDate": "Sun May 17 2020 00:02:37 GMT-0400 (Eastern Daylight Time)",
            "totalRevenue": 40,
            "totalHSTCollected": 5.2,
            "totalHSTSpent": 1.56,
            "totalExpenses": 12,
            "incomeTaxRate": 0.2,
            "numberOfOrders": 2,
        },
        {
            _id: "project2_id",
            userId: "person1_id",
            startDate: new Date().toString(),
            endDate: new Date().toString(),
            totalRevenue: 40,
            totalHSTCollected: 5.2,
            totalHSTSpent: 1.56,
            totalExpenses: 12,
            incomeTaxRate: 0.2,
            numberOfOrders: 2,
        },
    ],
    transfers: [
        {
            _id: "transfer1_id",
            userId: "person1_id",
            date: new Date().toString(),
            taxType: "hst",
            amount: 3.64,
            fromAccount: "Business Expenses",
            toAccount: "Tax Withholding",
        },

    ],

};
